name: Test addLabels Action

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run addLabels Action (multiline)
        uses: ./
        with:
          labels: |
            - hello
            - there
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Run addLabels Action (one line)
        uses: ./
        with:
          labels: 'feature'
          github_token: ${{ secrets.GITHUB_TOKEN }}
