name: Test addLabel Action

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run addLabel Action
        uses: ./
        with:
          labels: 'hello;there'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delimiter: ';'
